#pragma once
/* ------------------ */

//0x8 bytes (sizeof)
struct _RTL_AVL_TREE
{
    struct _RTL_BALANCED_NODE* Root;                                        //0x0
};
/* Used in */
// _EPROCESS
// _LOCK_HEADER
// _MI_COMBINE_PAGE_LISTHEAD
// _MI_COMBINE_STATE
// _MI_ENCLAVE_STATE
// _MI_HUGE_SYSTEM_VIEW_HEAD
// _MI_IO_PAGE_STATE
// _MI_PAGELIST_STATE
// _MI_PAGING_IO_STATE
// _MI_PARTITION_CORE
// _MI_PARTITION_PAGE_LISTS
// _MI_POOL_STATE
// _MI_SECTION_STATE
// _MI_SESSION_STATE
// _MI_SYSTEM_IMAGE_STATE
// _MI_SYSTEM_PTE_STATE
// _MMPAGING_FILE
// _MMSESSION
// _MM_SESSION_SPACE
// _PS_DYNAMIC_ENFORCED_ADDRESS_RANGES
// _SUBSECTION
// _WNF_SCOPE_INSTANCE

